--[[
	© DestructionSimulator [2025]
	ReplicatedStorage.Directory.Rebirths — Data-driven configuration for Rebirth levels & multipliers (Tiers 1 to 15).
--]]

return {
	[1] = {
		LevelRequired = 75,
		CashMultiplier = 1.2,
		BlocksMultiplier = 1.2,
		Description = "First Rebirth - Unlocks Flying Carpet & 1.2x Multiplier!"
	},
	[2] = {
		LevelRequired = 150,
		CashMultiplier = 1.5,
		BlocksMultiplier = 1.5,
		Description = "Second Rebirth - Unlocks 1.5x Multiplier!"
	},
	[3] = {
		LevelRequired = 200,
		CashMultiplier = 2.0,
		BlocksMultiplier = 2.0,
		Description = "Third Rebirth - Unlocks 2.0x Multiplier!"
	},
	[4] = {
		LevelRequired = 250,
		CashMultiplier = 2.5,
		BlocksMultiplier = 2.5,
		Description = "Fourth Rebirth - Unlocks 2.5x Multiplier!"
	},
	[5] = {
		LevelRequired = 300,
		CashMultiplier = 3.0,
		BlocksMultiplier = 3.0,
		Description = "Fifth Rebirth - Unlocks 3.0x Multiplier!"
	},
	[6] = {
		LevelRequired = 350,
		CashMultiplier = 3.5,
		BlocksMultiplier = 3.5,
		Description = "Sixth Rebirth - Unlocks 3.5x Multiplier!"
	},
	[7] = {
		LevelRequired = 400,
		CashMultiplier = 4.0,
		BlocksMultiplier = 4.0,
		Description = "Seventh Rebirth - Unlocks 4.0x Multiplier!"
	},
	[8] = {
		LevelRequired = 450,
		CashMultiplier = 4.5,
		BlocksMultiplier = 4.5,
		Description = "Eighth Rebirth - Unlocks 4.5x Multiplier!"
	},
	[9] = {
		LevelRequired = 500,
		CashMultiplier = 5.0,
		BlocksMultiplier = 5.0,
		Description = "Ninth Rebirth - Unlocks 5.0x Multiplier!"
	},
	[10] = {
		LevelRequired = 550,
		CashMultiplier = 6.0,
		BlocksMultiplier = 6.0,
		Description = "Tenth Rebirth - Unlocks 6.0x Multiplier!"
	},
	[11] = {
		LevelRequired = 600,
		CashMultiplier = 7.0,
		BlocksMultiplier = 7.0,
		Description = "Eleventh Rebirth - Unlocks 7.0x Multiplier!"
	},
	[12] = {
		LevelRequired = 650,
		CashMultiplier = 8.0,
		BlocksMultiplier = 8.0,
		Description = "Twelfth Rebirth - Unlocks 8.0x Multiplier!"
	},
	[13] = {
		LevelRequired = 700,
		CashMultiplier = 9.0,
		BlocksMultiplier = 9.0,
		Description = "Thirteenth Rebirth - Unlocks 9.0x Multiplier!"
	},
	[14] = {
		LevelRequired = 750,
		CashMultiplier = 10.0,
		BlocksMultiplier = 10.0,
		Description = "Fourteenth Rebirth - Unlocks 10.0x Multiplier!"
	},
	[15] = {
		LevelRequired = 800,
		CashMultiplier = 12.0,
		BlocksMultiplier = 12.0,
		Description = "Fifteenth Rebirth - Max Rebirth Level Reached (12.0x Multiplier)!"
	},
}
