return {
	name = "Elite Bastion Case",
	rarity = "Covert",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 100,
	skins = {
		["Urban DDPTA"] = {
			["Rocket Launcher"] = 10,
			["Classic Launcher"] = 10,
			["Arm Cannon"] = 10,
			["BambooRocket"] = 10,
		},
		["Pit Viber"] = {
			["EggLauncher"] = 10,
			["Firework Launcher"] = 10,
			["Golden Launcher"] = 10,
		},
		["Neo Fade"] = {
			["Bombardier"] = 2,
			["Bow"] = 2,
			["Crystal Blaster"] = 2,
		},
		["Gungnir"] = {
			["Golden Racket"] = 0.075,
			["Hoss Hog"] = 0.075,
		},
		["Special Backpack"] = 0.5,
	}
}