return {
	name = "Elite Vanguard Case",
	rarity = "Covert",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 100,
	skins = {
		["Urban DDPTA"] = {
			["Ice Cream Launcher"] = 15,
			["Kitty Launcher"] = 15,
			["Laser Cannon"] = 10,
			["Lunar Dragon"] = 10,
		},
		["Neo Fade"] = {
			["Rock Star"] = 12,
			["Scope Shot"] = 12,
			["Shadow Dragon"] = 10,
		},
		["Pit Viber"] = {
			["Spooky Staff"] = 8,
			["Starblaster"] = 8,
			["The Embezzler"] = 5,
		},
		["Gungnir"] = {
			["Pumpkin Bomb"] = 2.25,
			["Remote Detonator"] = 2.25,
		},
		["Special Backpack"] = 0.5,
	}
}