return {
	name = "Elite Core Case",
	rarity = "Covert",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 100,
	skins = {
		["Urban DDPTA"] = {
			["Bomb"] = 15,
			["Blast Bomb"] = 15,
			["Blast Potion"] = 10,
			["Bloom Bomb"] = 10,
		},
		["Neo Fade"] = {
			["Bug Bomb"] = 12,
			["Classic Bomb"] = 12,
			["Cool Sun"] = 10,
		},
		["Pit Viber"] = {
			["Crystal Bomb"] = 8,
			["Flower Bomb"] = 8,
			["Gem Bomb"] = 5,
		},
		["Gungnir"] = {
			["Gift Bomb"] = 2.25,
			["Nova Bomb"] = 2.25,
		},
		["Special Backpack"] = 0.5,
	}
}