return {
	name = "Essential Bastion Case",
	rarity = "Restricted",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 25,
	skins = {
		["Boreal Forest"] = {
			["Rocket Launcher"] = 20,
			["Classic Launcher"] = 20,
			["Arm Cannon"] = 15,
			["BambooRocket"] = 15,
			["Bombardier"] = 15,
			["Bow"] = 15,
		},
		["Safari"] = {
			["Bomb"] = 20,
			["Blast Bomb"] = 15,
			["Bloom Bomb"] = 15,
			["Bug Bomb"] = 15,
			["Classic Bomb"] = 15,
		},
		["Sand Dune"] = {
			["Crystal Blaster"] = 10,
			["EggLauncher"] = 10,
			["Firework Launcher"] = 10,
			["Cool Sun"] = 10,
		},
		["Urban DDPTA"] = {
			["Golden Launcher"] = 5,
			["Golden Racket"] = 5,
		},
		["Neo Fade"] = {
			["Hoss Hog"] = 3.7,
		},
		["Gungnir"] = {
			["Rocket Launcher"] = 0.05,
		},
		["Special Backpack"] = 0.25,
	}
}