return {
	name = "Essential Vanguard Case",
	rarity = "Restricted",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 25,
	skins = {
		["Boreal Forest"] = {
			["Rocket Launcher"] = 20,
			["Classic Launcher"] = 20,
			["Laser Cannon"] = 15,
			["Rock Star"] = 15,
		},
		["Safari"] = {
			["Bomb"] = 20,
			["Shadow Bomb"] = 15,
			["Shadow Shuriken"] = 15,
			["Square Bomb"] = 15,
			["Sticky Bomb"] = 15,
		},
		["Sand Dune"] = {
			["Sticky Potion"] = 10,
			["Super Bomb"] = 10,
			["Blast Potion"] = 10,
			["Arm Cannon"] = 10,
		},
		["Urban DDPTA"] = {
			["BambooRocket"] = 5,
			["Bombardier"] = 5,
		},
		["Neo Fade"] = {
			["Bow"] = 3.7,
		},
		["Gungnir"] = {
			["Bomb"] = 0.05,
		},
		["Special Backpack"] = 0.25,
	}
}