return {
	name = "Essential Core Case",
	rarity = "Restricted",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 25,
	skins = {
		["Safari"] = {
			["Crystal Bomb"] = 15,
			["Flower Bomb"] = 15,
			["Gem Bomb"] = 15,
			["Gift Bomb"] = 15,
		},
		["Boreal Forest"] = {
			["Ice Cream Launcher"] = 10,
			["Kitty Launcher"] = 10,
			["Laser Cannon"] = 10,
		},
		["Sand Dune"] = {
			["Scope Shot"] = 5,
			["Shadow Dragon"] = 4,
		},
		["Urban DDPTA"] = {
			["Starblaster"] = 0.6,
		},
		["Pit Viber"] = {
			["Pumpkin Bomb"] = 0.3,
		},
		["Neo Fade"] = {
			["Remote Detonator"] = 0.09,
		},
		["Gungnir"] = {
			["Classic Launcher"] = 0.01,
		},
		["Special Backpack"] = 0.05,
	}
}