return {
	name = "Forge Core Case",
	rarity = "Legendary",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 50,
	skins = {
		["Sand Dune"] = {
			["Bomb"] = 15,
			["Blast Bomb"] = 15,
			["Blast Potion"] = 10,
			["Bloom Bomb"] = 10,
		},
		["Urban DDPTA"] = {
			["Bug Bomb"] = 15,
			["Classic Bomb"] = 15,
			["Cool Sun"] = 10,
			["Crystal Bomb"] = 10,
		},
		["Neo Fade"] = {
			["Flower Bomb"] = 10,
			["Gem Bomb"] = 10,
			["Gift Bomb"] = 5,
		},
		["Pit Viber"] = {
			["Nova Bomb"] = 4,
			["Pumpkin Bomb"] = 4,
		},
		["Gungnir"] = {
			["Bomb"] = 1.7,
		},
		["Special Backpack"] = 0.3,
	}
}