return {
	name = "Forge Bastion Case",
	rarity = "Legendary",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 50,
	skins = {
		["Sand Dune"] = {
			["Rocket Launcher"] = 12,
			["Classic Launcher"] = 12,
			["Arm Cannon"] = 10,
			["BambooRocket"] = 10,
		},
		["Urban DDPTA"] = {
			["Bombardier"] = 10,
			["Bow"] = 10,
			["Crystal Blaster"] = 10,
			["EggLauncher"] = 10,
		},
		["Pit Viber"] = {
			["Firework Launcher"] = 7,
			["Golden Launcher"] = 7,
		},
		["Neo Fade"] = {
			["Golden Racket"] = 1.2,
			["Hoss Hog"] = 0.5,
		},
		["Gungnir"] = {
			["Rocket Launcher"] = 0.1,
		},
		["Special Backpack"] = 0.2,
	}
}