return {
	name = "Forge Vanguard Case",
	rarity = "Legendary",
	icon = "rbxassetid://107176774095927",
	imageId = "rbxassetid://107176774095927",
	price = 50,
	skins = {
		["Sand Dune"] = {
			["Kitty Launcher"] = 15,
			["Laser Cannon"] = 15,
			["Lunar Dragon"] = 10,
			["Rock Star"] = 10,
		},
		["Urban DDPTA"] = {
			["Scope Shot"] = 15,
			["Shadow Dragon"] = 15,
			["Spooky Staff"] = 10,
			["Starblaster"] = 10,
		},
		["Neo Fade"] = {
			["The Embezzler"] = 10,
			["Remote Detonator"] = 10,
			["Shadow Bomb"] = 5,
		},
		["Pit Viber"] = {
			["Shadow Shuriken"] = 4,
			["Square Bomb"] = 4,
		},
		["Gungnir"] = {
			["Laser Cannon"] = 1.7,
		},
		["Special Backpack"] = 0.3,
	}
}