return {
	price = 70000,
	layoutOrder = 9,
	reload = 1.5,
	speed = 75,
	power = 700,
	blastRadius = 11,
	brickMultiplier = 1.75,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = true,
	baseProjectile = "Rocket",
	projectile = "BusterShot",
	explodeParticle = "BusterExplosions",

	sounds = {
		Fire = 100435571625533,
		Reload = 93535777617414,
		Charge = 80224034004982,
		FireCharged = 91698868776700,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 81330840629229,
	},
}
