return {
	price = 5750000,
	layoutOrder = 20,
	reload = 3,
	speed = 75,
	power = 18000,
	blastRadius = 18,
	brickMultiplier = 12.5,
	bombJumpMultiplier = 1.56,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "BambooRocket",
	explodeParticle = "Fireworks",

	sounds = {
		Fire = 98363220720181,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 81330840629229,
	},
}
