return {
	price = 850,
	layoutOrder = 3,
	reload = 4.2,
	speed = 75,
	power = 25,
	blastRadius = 5,
	brickMultiplier = 0.43,
	bombJumpMultiplier = 1.56,
	gravity = 0.25,
	noAmmoDummy = false,
	baseProjectile = "BombRocket",
	projectile = "BombRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 134725381378233,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
