return {
	price = 400000,
	layoutOrder = 14,
	reload = 1.5,
	speed = 100,
	power = 3000,
	blastRadius =79,
	brickMultiplier = 1.5,
	bombJumpMultiplier = 0.78,
	gravity = 0.4,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "ArrowBig",
	explodeParticle = "BusterExplosions",

	sounds = {
		Fire = 104827521600910,
		Reload = 84828613930118,
		Charge = 133297597604853,
		FireCharged = 110162738594874,
	},
	animations = {
		Fire = 98796355925866,
		Reload = 90459419850787,
		Idle = 107890334015763,
	},
}
