return {
	price = 50000000,
	layoutOrder = 22,
	reload = 3,
	speed = 75,
	power = 35000,
	blastRadius = 26,
	brickMultiplier = 18,
	bombJumpMultiplier = 1,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "ClassicRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 108666329732912,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
