return {
	price = 95000,
	layoutOrder = 10,
	reload = 4.4,
	speed = 75,
	power = 950,
	blastRadius = 12,
	brickMultiplier = 2,
	bombJumpMultiplier = 1.11,
	gravity = 0,
	noAmmoDummy = true,
	baseProjectile = "Rocket",
	projectile = "CrystalRocket",
	explodeParticle = "CrystalExplosions",

	sounds = {
		Fire = 124136931207748,
		Reload = 118356309147632,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 81330840629229,
	},
}
