return {
	price = 250,
	layoutOrder = 2,
	reload = 3.5,
	speed = 75,
	power = 10,
	blastRadius = 4,
	brickMultiplier = 0.26,
	bombJumpMultiplier = 1.44,
	gravity = 0.4,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "EggRocket",
	explodeParticle = "Fireworks",

	sounds = {
		Fire = 77665928044688,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
