return {
	price = 5500,
	layoutOrder = 5,
	reload = 3,
	speed = 75,
	power = 120,
	blastRadius = 7,
	brickMultiplier = 0.85,
	bombJumpMultiplier = 1.56,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "RocketFirework",
	explodeParticle = "Fireworks",

	sounds = {
		Fire = 98363220720181,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
