return {
	price = 2200,
	layoutOrder = 4,
	reload = 3,
	speed = 75,
	power = 60,
	blastRadius = 6,
	brickMultiplier = 0.51,
	bombJumpMultiplier = 1,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "GoldRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 77665928044688,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
