return {
	price = 2200000,
	layoutOrder = 18,
	reload = 2,
	speed = 75,
	power = 8000,
	blastRadius = 15,
	brickMultiplier = 5.5,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "TennisBall",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 107828123702093,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 130752145106709,
		Reload = 90459419850787,
		Idle = 107890334015763,
	},
}
