return {
	price = 4000000,
	layoutOrder = 19,
	reload = 4.1,
	speed = 75,
	power = 12500,
	blastRadius = 17,
	brickMultiplier = 10,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "EngineRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 78439458440418,
		Reload = 95351208279627,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
