return {
	price = 25000,
	layoutOrder = 7,
	reload = 3,
	speed = 75,
	power = 250,
	blastRadius = 6,
	brickMultiplier = 0.72,
	bombJumpMultiplier = 1.56,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "IceCreamRocket",
	explodeParticle = "IceCreamExplosions",

	sounds = {
		Fire = 77665928044688,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
