return {
	price = 45000,
	layoutOrder = 8,
	reload = 3,
	speed = 75,
	power = 350,
	blastRadius = 8,
	brickMultiplier = 1.6,
	bombJumpMultiplier = 1.56,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "CatRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 134359142063796,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
