return {
	price = 122500,
	layoutOrder = 11,
	reload = 3.9,
	speed = 75,
	power = 1250,
	blastRadius = 13,
	brickMultiplier = 2.95,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "LaserRocket",
	projectile = "LaserRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 104035093810105,
		Reload = 139853074898147,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
