return {
	price = 150000,
	layoutOrder = 12,
	reload = 3,
	speed = 75,
	power = 2250,
	blastRadius = 16,
	brickMultiplier = 4.4,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "LunarRocket",
	explodeParticle = "Fireworks",

	sounds = {
		Fire = 83052956211649,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
