return {
	price = 0,
	layoutOrder = 1,
	reload = 3,
	speed = 75,
	power = 5,
	blastRadius = 3,
	brickMultiplier = 0.2,
	bombJumpMultiplier = 1,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "Rocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 77665928044688,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
