return {
	price = 1450000,
	layoutOrder = 17,
	reload = 3.6,
	speed = 28,
	power = 6400,
	blastRadius = 16,
	brickMultiplier = 7.5,
	bombJumpMultiplier = 1.33,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "SpaceRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 82210430355506,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
