return {
	price = 275000,
	layoutOrder = 13,
	reload = 3.8,
	speed = 50,
	power = 2500,
	blastRadius = 14,
	brickMultiplier = 4.25,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "ShadowRocket",
	explodeParticle = "ShadowExplosions",

	sounds = {
		Fire = 83052956211649,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
