return {
	price = 12500,
	layoutOrder = 6,
	reload = 3,
	speed = 75,
	power = 375,
	blastRadius = 8,
	brickMultiplier = 1.5,
	bombJumpMultiplier = 1.56,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "SkullRocket",
	explodeParticle = "Explosions",

	sounds = {
		Fire = 93593293515085,
		Reload = 86039598131923,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
