return {
	price = 10000000,
	layoutOrder = 21,
	reload = 3,
	speed = 75,
	power = 30000,
	blastRadius = 24,
	brickMultiplier = 16,
	bombJumpMultiplier = 1.78,
	gravity = 0.3,
	noAmmoDummy = false,
	baseProjectile = "BombRocket",
	projectile = "StarRocket",
	explodeParticle = "StarExplosions",

	sounds = {
		Fire = 102407319558240,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
