return {
	price = 650000,
	layoutOrder = 15,
	reload = 3,
	speed = 75,
	power = 3600,
	blastRadius = 14,
	brickMultiplier = 3.75,
	bombJumpMultiplier = 1.44,
	gravity = 0,
	noAmmoDummy = false,
	baseProjectile = "Rocket",
	projectile = "EmbezzlerRocket",
	explodeParticle = "EmbezzlerExplosions",

	sounds = {
		Fire = 97323089164653,
		Reload = 93535777617414,
	},
	animations = {
		Fire = 126196362232460,
		Reload = 90459419850787,
	},
}
