return {
	Name = "Magic",
	DisplayName = "Magic World",
	Order = 2,
	MainValue = "GalaxyBlocks",
	WorldMultiplier = 2.5,
	RequiredRebirths = 1,
	RequiredLevel = 75,
	Disabled = false,
	Launcher = {
		"Lunar Dragon", --12
		"Shadow Dragon", --13
		"Bow", --14
		"The Embezzler", --15
		"Rock Star", --16
		"Scope Shot", --17
		"Golden Racket", --18
		"Hoss Hog", --19
		"BambooRocket", --20
		"Starblaster", --21
		"Classic Launcher", --22
	},
	Bomb = {
		"Nova Bomb", --12
		"Crystal Bomb", --13
		"Classic Bomb", --14
		"Sticky Bomb", --15
		"Super Bomb", --16
		"Blast Potion", --17
		"Cool Sun", --18
		"Remote Detonator", --19
		"Sticky Potion", --20
	},
	Backpack = {
		"Canister", --12
		"DoubleCanister", --13
		"TecBag", --14
		"BigCarnier", --15
		"MniValt", --16
		"Valt", --17
		"BigValt", --18
		"MiniSafe", --19
		"Safe", --20
		"BigSafe", --21
	},
	Music = { 85533156796296, 78342014715596 },
}
