return {
	Name = "Spawn",
	DisplayName = "Spawn World",
	Order = 1,
	MainValue = "Blocks",
	WorldMultiplier = 1.0,
	Launcher = {
		"EggLauncher", --2
		"Bombardier", --3
		"Golden Launcher", --4
		"Firework Launcher", --5
		"Spooky Staff", --6
		"Ice Cream Launcher", --7
		"Kitty Launcher", --8
		"Arm Cannon", --9
		"Crystal Blaster", --10
		"Laser Cannon", --11
	},
	Bomb = {
		"Flower Bomb", --2
		"Pumpkin Bomb", --3
		"Bloom Bomb", --4
		"Bug Bomb", --5
		"Gift Bomb", --6
		"Gem Bomb", --7
		"Blast Bomb", --8
		"Square Bomb", --9
		"Shadow Bomb", --10
		"Shadow Shuriken", --11
	},
	Backpack = {
		"SmallBag", --1
		"MediumBag", --2
		"LargeBag", --3
		"TravelBag", --4
		"CampingBag", --5
		"DeluxBag", --7
		"FridgeBag", --8
		"MiniBarrel", --9
		"Barrel", --10
		"BigBarrel", --11
	},
	Music = { 85533156796296 },
}
