local Data = {
	-- RunFaster Upgrades (Tiers 1 to 5)
	["RunFaster1"] = { ID = 3708247643 },
	["RunFaster2"] = { ID = 3708247810 },
	["RunFaster3"] = { ID = 3708247927 },
	["RunFaster4"] = { ID = 3708248036 },
	["RunFaster5"] = { ID = 3708248695 },
	
	-- Magnet Upgrades (Tiers 1 to 5)
	["Magnet1"] = { ID = 3708248973 },
	["Magnet2"] = { ID = 3708249076 },
	["Magnet3"] = { ID = 3708249157 },
	["Magnet4"] = { ID = 3708249264 },
	["Magnet5"] = { ID = 3708249325 },
}

return Data
